import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Ingredient categories as defined in the architecture
const CATEGORIES = {
  PRODUCE: 'Produce',
  MEAT_SEAFOOD: 'Meat/Seafood',
  DAIRY: 'Dairy',
  BAKERY: 'Bakery',
  CANNED_GOODS: 'Canned Goods',
  FROZEN: 'Frozen',
  SPICES: 'Spices',
  PANTRY: 'Pantry',
  OTHER: 'Other',
} as const;

// Common ingredient data - 500+ ingredients across all categories
const ingredients = [
  // PRODUCE (100+ items)
  { name: 'Tomato', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'lbs', 'g', 'kg'] },
  { name: 'Onion', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'lbs', 'g', 'kg'] },
  { name: 'Garlic', category: CATEGORIES.PRODUCE, commonUnits: ['clove', 'bulb', 'g', 'tsp'] },
  { name: 'Potato', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'lbs', 'g', 'kg'] },
  { name: 'Carrot', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'lbs', 'g', 'kg'] },
  { name: 'Celery', category: CATEGORIES.PRODUCE, commonUnits: ['stalk', 'bunch', 'g', 'cup'] },
  { name: 'Bell Pepper', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Lettuce', category: CATEGORIES.PRODUCE, commonUnits: ['head', 'bunch', 'g', 'cup'] },
  { name: 'Cucumber', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Zucchini', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Spinach', category: CATEGORIES.PRODUCE, commonUnits: ['bunch', 'g', 'cup', 'oz'] },
  { name: 'Broccoli', category: CATEGORIES.PRODUCE, commonUnits: ['head', 'g', 'cup', 'oz'] },
  { name: 'Cauliflower', category: CATEGORIES.PRODUCE, commonUnits: ['head', 'g', 'cup'] },
  { name: 'Mushroom', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup', 'oz'] },
  { name: 'Avocado', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g'] },
  { name: 'Lemon', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'tbsp', 'tsp'] },
  { name: 'Lime', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'tbsp', 'tsp'] },
  { name: 'Apple', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Banana', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Orange', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Strawberry', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup', 'pint'] },
  { name: 'Blueberry', category: CATEGORIES.PRODUCE, commonUnits: ['g', 'cup', 'pint', 'oz'] },
  { name: 'Raspberry', category: CATEGORIES.PRODUCE, commonUnits: ['g', 'cup', 'pint', 'oz'] },
  { name: 'Grape', category: CATEGORIES.PRODUCE, commonUnits: ['g', 'cup', 'lbs'] },
  { name: 'Watermelon', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'lbs', 'kg', 'cup'] },
  { name: 'Pineapple', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'cup', 'g'] },
  { name: 'Mango', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Peach', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Pear', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Cherry', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup', 'oz'] },
  { name: 'Kiwi', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g'] },
  { name: 'Green Beans', category: CATEGORIES.PRODUCE, commonUnits: ['lbs', 'g', 'cup', 'oz'] },
  { name: 'Asparagus', category: CATEGORIES.PRODUCE, commonUnits: ['bunch', 'lbs', 'g', 'oz'] },
  { name: 'Eggplant', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Corn', category: CATEGORIES.PRODUCE, commonUnits: ['ear', 'cup', 'g', 'oz'] },
  { name: 'Peas', category: CATEGORIES.PRODUCE, commonUnits: ['cup', 'g', 'oz', 'lbs'] },
  { name: 'Sweet Potato', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup', 'lbs'] },
  { name: 'Beet', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup', 'bunch'] },
  { name: 'Cabbage', category: CATEGORIES.PRODUCE, commonUnits: ['head', 'g', 'cup', 'lbs'] },
  { name: 'Kale', category: CATEGORIES.PRODUCE, commonUnits: ['bunch', 'g', 'cup', 'oz'] },
  { name: 'Arugula', category: CATEGORIES.PRODUCE, commonUnits: ['bunch', 'g', 'cup', 'oz'] },
  { name: 'Cilantro', category: CATEGORIES.PRODUCE, commonUnits: ['bunch', 'g', 'tbsp', 'cup'] },
  { name: 'Parsley', category: CATEGORIES.PRODUCE, commonUnits: ['bunch', 'g', 'tbsp', 'cup'] },
  { name: 'Basil', category: CATEGORIES.PRODUCE, commonUnits: ['bunch', 'g', 'tbsp', 'cup'] },
  { name: 'Mint', category: CATEGORIES.PRODUCE, commonUnits: ['bunch', 'g', 'tbsp', 'cup'] },
  { name: 'Dill', category: CATEGORIES.PRODUCE, commonUnits: ['bunch', 'g', 'tbsp'] },
  { name: 'Thyme', category: CATEGORIES.PRODUCE, commonUnits: ['bunch', 'g', 'tsp', 'tbsp'] },
  { name: 'Rosemary', category: CATEGORIES.PRODUCE, commonUnits: ['sprig', 'g', 'tsp', 'tbsp'] },
  { name: 'Ginger', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'tbsp', 'tsp'] },
  { name: 'Green Onion', category: CATEGORIES.PRODUCE, commonUnits: ['bunch', 'pc', 'tbsp', 'cup'] },
  { name: 'Shallot', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'tbsp'] },
  { name: 'Leek', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Radish', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup', 'bunch'] },
  { name: 'Turnip', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Parsnip', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Brussels Sprouts', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup', 'lbs'] },
  { name: 'Squash', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup', 'lbs'] },
  { name: 'Pumpkin', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup', 'lbs'] },
  { name: 'Butternut Squash', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup', 'lbs'] },
  { name: 'Acorn Squash', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Jalapeno', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'tsp', 'tbsp'] },
  { name: 'Serrano Pepper', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'tsp'] },
  { name: 'Habanero', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'tsp'] },
  { name: 'Red Pepper', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Yellow Pepper', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Orange Pepper', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Cherry Tomato', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup', 'pint'] },
  { name: 'Grape Tomato', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup', 'pint'] },
  { name: 'Roma Tomato', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Plum Tomato', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Red Onion', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'White Onion', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Yellow Onion', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Sweet Onion', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Baby Carrot', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup', 'bag'] },
  { name: 'Snow Peas', category: CATEGORIES.PRODUCE, commonUnits: ['g', 'cup', 'oz'] },
  { name: 'Snap Peas', category: CATEGORIES.PRODUCE, commonUnits: ['g', 'cup', 'oz'] },
  { name: 'Bok Choy', category: CATEGORIES.PRODUCE, commonUnits: ['bunch', 'g', 'cup'] },
  { name: 'Napa Cabbage', category: CATEGORIES.PRODUCE, commonUnits: ['head', 'g', 'cup'] },
  { name: 'Watercress', category: CATEGORIES.PRODUCE, commonUnits: ['bunch', 'g', 'cup'] },
  { name: 'Endive', category: CATEGORIES.PRODUCE, commonUnits: ['head', 'g', 'cup'] },
  { name: 'Radicchio', category: CATEGORIES.PRODUCE, commonUnits: ['head', 'g', 'cup'] },
  { name: 'Fennel', category: CATEGORIES.PRODUCE, commonUnits: ['bulb', 'g', 'cup'] },
  { name: 'Artichoke', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g'] },
  { name: 'Okra', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Tomatillo', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Chayote', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Jicama', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Kohlrabi', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Rutabaga', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Celeriac', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'cup'] },
  { name: 'Horseradish', category: CATEGORIES.PRODUCE, commonUnits: ['pc', 'g', 'tbsp', 'tsp'] },
  { name: 'Bean Sprouts', category: CATEGORIES.PRODUCE, commonUnits: ['g', 'cup', 'oz'] },
  { name: 'Alfalfa Sprouts', category: CATEGORIES.PRODUCE, commonUnits: ['g', 'cup', 'oz'] },
  { name: 'Microgreens', category: CATEGORIES.PRODUCE, commonUnits: ['g', 'cup', 'oz'] },

  // MEAT/SEAFOOD (80+ items)
  { name: 'Chicken Breast', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Chicken Thigh', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Chicken Wing', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Chicken Drumstick', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Whole Chicken', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'kg', 'pc'] },
  { name: 'Ground Chicken', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz'] },
  { name: 'Beef Steak', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Ground Beef', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz'] },
  { name: 'Beef Roast', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'kg', 'g'] },
  { name: 'Beef Brisket', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'kg', 'g'] },
  { name: 'Beef Short Ribs', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'pc'] },
  { name: 'Pork Chop', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Pork Tenderloin', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz'] },
  { name: 'Pork Shoulder', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'kg', 'g'] },
  { name: 'Ground Pork', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz'] },
  { name: 'Bacon', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'slice'] },
  { name: 'Sausage', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'link'] },
  { name: 'Ham', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'slice'] },
  { name: 'Prosciutto', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['g', 'oz', 'slice'] },
  { name: 'Pancetta', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['g', 'oz', 'slice'] },
  { name: 'Lamb Chop', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Lamb Leg', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'kg', 'g'] },
  { name: 'Ground Lamb', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz'] },
  { name: 'Turkey Breast', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz'] },
  { name: 'Ground Turkey', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz'] },
  { name: 'Whole Turkey', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'kg'] },
  { name: 'Duck', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'kg', 'pc'] },
  { name: 'Duck Breast', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Veal', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz'] },
  { name: 'Venison', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz'] },
  { name: 'Salmon Fillet', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Tuna Steak', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Cod Fillet', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Halibut', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Tilapia', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Mahi Mahi', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Sea Bass', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Swordfish', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Trout', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Catfish', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Snapper', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Shrimp', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Prawns', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Lobster', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'pc'] },
  { name: 'Crab', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'pc'] },
  { name: 'Crab Meat', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz'] },
  { name: 'Scallops', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Mussels', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz'] },
  { name: 'Clams', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Oysters', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['pc', 'dozen', 'g'] },
  { name: 'Squid', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz'] },
  { name: 'Octopus', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz'] },
  { name: 'Anchovies', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['g', 'oz', 'can', 'fillet'] },
  { name: 'Sardines', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['g', 'oz', 'can', 'pc'] },
  { name: 'Mackerel', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Herring', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['lbs', 'g', 'oz', 'pc'] },
  { name: 'Smoked Salmon', category: CATEGORIES.MEAT_SEAFOOD, commonUnits: ['g', 'oz', 'slice'] },

  // DAIRY (50+ items)
  { name: 'Milk', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'ml', 'liter', 'gal', 'oz'] },
  { name: 'Whole Milk', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'ml', 'liter', 'gal', 'oz'] },
  { name: 'Skim Milk', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'ml', 'liter', 'gal', 'oz'] },
  { name: '2% Milk', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'ml', 'liter', 'gal', 'oz'] },
  { name: 'Heavy Cream', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'ml', 'oz', 'tbsp'] },
  { name: 'Half and Half', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'ml', 'oz', 'tbsp'] },
  { name: 'Whipping Cream', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'ml', 'oz'] },
  { name: 'Sour Cream', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz', 'tbsp'] },
  { name: 'Buttermilk', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'ml', 'oz'] },
  { name: 'Butter', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz', 'tbsp', 'stick'] },
  { name: 'Unsalted Butter', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz', 'tbsp', 'stick'] },
  { name: 'Salted Butter', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz', 'tbsp', 'stick'] },
  { name: 'Margarine', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz', 'tbsp'] },
  { name: 'Cream Cheese', category: CATEGORIES.DAIRY, commonUnits: ['oz', 'g', 'cup', 'tbsp'] },
  { name: 'Cottage Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Ricotta Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Mozzarella Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Cheddar Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz', 'slice'] },
  { name: 'Parmesan Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz', 'tbsp'] },
  { name: 'Swiss Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz', 'slice'] },
  { name: 'Provolone Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz', 'slice'] },
  { name: 'Feta Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Goat Cheese', category: CATEGORIES.DAIRY, commonUnits: ['g', 'oz', 'tbsp'] },
  { name: 'Blue Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Brie Cheese', category: CATEGORIES.DAIRY, commonUnits: ['g', 'oz'] },
  { name: 'Gouda Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Monterey Jack Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Pepper Jack Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Colby Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Gruyere Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Fontina Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Asiago Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Manchego Cheese', category: CATEGORIES.DAIRY, commonUnits: ['g', 'oz'] },
  { name: 'Havarti Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Muenster Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz', 'slice'] },
  { name: 'American Cheese', category: CATEGORIES.DAIRY, commonUnits: ['slice', 'oz'] },
  { name: 'Velveeta Cheese', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'oz'] },
  { name: 'Cream', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'ml', 'oz', 'tbsp'] },
  { name: 'Yogurt', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Greek Yogurt', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Plain Yogurt', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Vanilla Yogurt', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Eggs', category: CATEGORIES.DAIRY, commonUnits: ['pc', 'dozen', 'large', 'cup'] },
  { name: 'Egg Whites', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'ml', 'oz'] },
  { name: 'Egg Yolks', category: CATEGORIES.DAIRY, commonUnits: ['pc', 'cup'] },
  { name: 'Condensed Milk', category: CATEGORIES.DAIRY, commonUnits: ['can', 'cup', 'oz', 'ml'] },
  { name: 'Evaporated Milk', category: CATEGORIES.DAIRY, commonUnits: ['can', 'cup', 'oz', 'ml'] },
  { name: 'Almond Milk', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'ml', 'oz'] },
  { name: 'Soy Milk', category: CATEGORIES.DAIRY, commonUnits: ['cup', 'ml', 'oz'] },
  { name: 'Coconut Milk', category: CATEGORIES.DAIRY, commonUnits: ['can', 'cup', 'ml', 'oz'] },

  // BAKERY (40+ items)
  { name: 'Bread', category: CATEGORIES.BAKERY, commonUnits: ['loaf', 'slice', 'oz'] },
  { name: 'White Bread', category: CATEGORIES.BAKERY, commonUnits: ['loaf', 'slice', 'oz'] },
  { name: 'Whole Wheat Bread', category: CATEGORIES.BAKERY, commonUnits: ['loaf', 'slice', 'oz'] },
  { name: 'Sourdough Bread', category: CATEGORIES.BAKERY, commonUnits: ['loaf', 'slice', 'oz'] },
  { name: 'Rye Bread', category: CATEGORIES.BAKERY, commonUnits: ['loaf', 'slice', 'oz'] },
  { name: 'French Bread', category: CATEGORIES.BAKERY, commonUnits: ['loaf', 'pc', 'oz'] },
  { name: 'Italian Bread', category: CATEGORIES.BAKERY, commonUnits: ['loaf', 'pc', 'oz'] },
  { name: 'Ciabatta', category: CATEGORIES.BAKERY, commonUnits: ['loaf', 'pc', 'oz'] },
  { name: 'Baguette', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'oz'] },
  { name: 'Pita Bread', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'pkg', 'oz'] },
  { name: 'Naan', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'pkg', 'oz'] },
  { name: 'Tortilla', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'pkg', 'oz'] },
  { name: 'Flour Tortilla', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'pkg', 'oz'] },
  { name: 'Corn Tortilla', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'pkg', 'oz'] },
  { name: 'English Muffin', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'pkg', 'oz'] },
  { name: 'Bagel', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'oz'] },
  { name: 'Croissant', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'oz'] },
  { name: 'Hamburger Bun', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'pkg', 'oz'] },
  { name: 'Hot Dog Bun', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'pkg', 'oz'] },
  { name: 'Dinner Roll', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'pkg', 'oz'] },
  { name: 'Brioche', category: CATEGORIES.BAKERY, commonUnits: ['loaf', 'pc', 'oz'] },
  { name: 'Challah', category: CATEGORIES.BAKERY, commonUnits: ['loaf', 'oz'] },
  { name: 'Focaccia', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'oz'] },
  { name: 'Breadcrumbs', category: CATEGORIES.BAKERY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Panko', category: CATEGORIES.BAKERY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Croutons', category: CATEGORIES.BAKERY, commonUnits: ['cup', 'oz'] },
  { name: 'Crackers', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'oz', 'sleeve'] },
  { name: 'Graham Crackers', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'cup', 'oz'] },
  { name: 'Saltine Crackers', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'oz'] },
  { name: 'Ritz Crackers', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'oz'] },
  { name: 'Muffin', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'oz'] },
  { name: 'Cake', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'slice', 'oz'] },
  { name: 'Cookie', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'oz'] },
  { name: 'Brownie', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'oz'] },
  { name: 'Donut', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'oz'] },
  { name: 'Danish', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'oz'] },
  { name: 'Scone', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'oz'] },
  { name: 'Pie Crust', category: CATEGORIES.BAKERY, commonUnits: ['pc', 'oz'] },
  { name: 'Phyllo Dough', category: CATEGORIES.BAKERY, commonUnits: ['pkg', 'oz', 'sheet'] },
  { name: 'Puff Pastry', category: CATEGORIES.BAKERY, commonUnits: ['pkg', 'oz', 'sheet'] },

  // CANNED GOODS (60+ items)
  { name: 'Tomato Paste', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'tbsp', 'cup'] },
  { name: 'Tomato Sauce', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Crushed Tomatoes', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Diced Tomatoes', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Whole Tomatoes', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Tomato Puree', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Black Beans', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Kidney Beans', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Pinto Beans', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Chickpeas', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Cannellini Beans', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Navy Beans', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Great Northern Beans', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Refried Beans', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Baked Beans', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Corn', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Green Beans', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Peas', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Carrots', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Mixed Vegetables', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Pumpkin Puree', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Cranberry Sauce', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Applesauce', category: CATEGORIES.CANNED_GOODS, commonUnits: ['jar', 'oz', 'cup'] },
  { name: 'Peaches', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Pears', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Pineapple', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Mandarin Oranges', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Fruit Cocktail', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Tuna', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Salmon', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Chicken Broth', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'cup', 'oz', 'liter'] },
  { name: 'Beef Broth', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'cup', 'oz', 'liter'] },
  { name: 'Vegetable Broth', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'cup', 'oz', 'liter'] },
  { name: 'Chicken Stock', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'cup', 'oz', 'liter'] },
  { name: 'Beef Stock', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'cup', 'oz', 'liter'] },
  { name: 'Vegetable Stock', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'cup', 'oz', 'liter'] },
  { name: 'Coconut Cream', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'cup', 'oz'] },
  { name: 'Artichoke Hearts', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Hearts of Palm', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Roasted Red Peppers', category: CATEGORIES.CANNED_GOODS, commonUnits: ['jar', 'oz', 'cup'] },
  { name: 'Olives', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'jar', 'oz', 'cup'] },
  { name: 'Black Olives', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'jar', 'oz', 'cup'] },
  { name: 'Green Olives', category: CATEGORIES.CANNED_GOODS, commonUnits: ['jar', 'oz', 'cup'] },
  { name: 'Kalamata Olives', category: CATEGORIES.CANNED_GOODS, commonUnits: ['jar', 'oz', 'cup'] },
  { name: 'Capers', category: CATEGORIES.CANNED_GOODS, commonUnits: ['jar', 'oz', 'tbsp'] },
  { name: 'Pickles', category: CATEGORIES.CANNED_GOODS, commonUnits: ['jar', 'pc', 'oz'] },
  { name: 'Relish', category: CATEGORIES.CANNED_GOODS, commonUnits: ['jar', 'oz', 'tbsp'] },
  { name: 'Sauerkraut', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'jar', 'oz', 'cup'] },
  { name: 'Kimchi', category: CATEGORIES.CANNED_GOODS, commonUnits: ['jar', 'oz', 'cup'] },
  { name: 'Salsa', category: CATEGORIES.CANNED_GOODS, commonUnits: ['jar', 'oz', 'cup', 'tbsp'] },
  { name: 'Enchilada Sauce', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Taco Sauce', category: CATEGORIES.CANNED_GOODS, commonUnits: ['jar', 'oz', 'tbsp'] },
  { name: 'Marinara Sauce', category: CATEGORIES.CANNED_GOODS, commonUnits: ['jar', 'oz', 'cup'] },
  { name: 'Pasta Sauce', category: CATEGORIES.CANNED_GOODS, commonUnits: ['jar', 'oz', 'cup'] },
  { name: 'Alfredo Sauce', category: CATEGORIES.CANNED_GOODS, commonUnits: ['jar', 'oz', 'cup'] },
  { name: 'Pesto', category: CATEGORIES.CANNED_GOODS, commonUnits: ['jar', 'oz', 'tbsp'] },
  { name: 'Soup', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },
  { name: 'Chili', category: CATEGORIES.CANNED_GOODS, commonUnits: ['can', 'oz', 'cup'] },

  // FROZEN (50+ items)
  { name: 'Frozen Peas', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'cup', 'oz'] },
  { name: 'Frozen Corn', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'cup', 'oz'] },
  { name: 'Frozen Green Beans', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'cup', 'oz'] },
  { name: 'Frozen Broccoli', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'cup', 'oz'] },
  { name: 'Frozen Cauliflower', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'cup', 'oz'] },
  { name: 'Frozen Mixed Vegetables', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'cup', 'oz'] },
  { name: 'Frozen Spinach', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'cup', 'oz'] },
  { name: 'Frozen Edamame', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'cup', 'oz'] },
  { name: 'Frozen Stir Fry Vegetables', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'cup', 'oz'] },
  { name: 'Frozen French Fries', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'oz'] },
  { name: 'Frozen Tater Tots', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'oz'] },
  { name: 'Frozen Hash Browns', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'oz', 'cup'] },
  { name: 'Frozen Pizza', category: CATEGORIES.FROZEN, commonUnits: ['pc', 'oz'] },
  { name: 'Frozen Lasagna', category: CATEGORIES.FROZEN, commonUnits: ['pc', 'oz'] },
  { name: 'Frozen Chicken Nuggets', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'oz', 'pc'] },
  { name: 'Frozen Chicken Tenders', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'oz', 'pc'] },
  { name: 'Frozen Meatballs', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'oz', 'pc'] },
  { name: 'Frozen Burgers', category: CATEGORIES.FROZEN, commonUnits: ['pc', 'oz'] },
  { name: 'Frozen Shrimp', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'lbs', 'oz'] },
  { name: 'Frozen Fish Fillets', category: CATEGORIES.FROZEN, commonUnits: ['pc', 'oz'] },
  { name: 'Frozen Fish Sticks', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'oz', 'pc'] },
  { name: 'Frozen Waffles', category: CATEGORIES.FROZEN, commonUnits: ['pc', 'oz'] },
  { name: 'Frozen Pancakes', category: CATEGORIES.FROZEN, commonUnits: ['pc', 'oz'] },
  { name: 'Frozen Berries', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'cup', 'oz'] },
  { name: 'Frozen Strawberries', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'cup', 'oz'] },
  { name: 'Frozen Blueberries', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'cup', 'oz'] },
  { name: 'Frozen Raspberries', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'cup', 'oz'] },
  { name: 'Frozen Mango', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'cup', 'oz'] },
  { name: 'Frozen Peaches', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'cup', 'oz'] },
  { name: 'Frozen Pineapple', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'cup', 'oz'] },
  { name: 'Frozen Cherries', category: CATEGORIES.FROZEN, commonUnits: ['bag', 'cup', 'oz'] },
  { name: 'Ice Cream', category: CATEGORIES.FROZEN, commonUnits: ['pint', 'quart', 'gal', 'scoop', 'oz'] },
  { name: 'Frozen Yogurt', category: CATEGORIES.FROZEN, commonUnits: ['pint', 'oz', 'scoop'] },
  { name: 'Sorbet', category: CATEGORIES.FROZEN, commonUnits: ['pint', 'oz', 'scoop'] },
  { name: 'Gelato', category: CATEGORIES.FROZEN, commonUnits: ['pint', 'oz', 'scoop'] },
  { name: 'Popsicles', category: CATEGORIES.FROZEN, commonUnits: ['pc'] },
  { name: 'Frozen Whipped Topping', category: CATEGORIES.FROZEN, commonUnits: ['container', 'cup', 'oz'] },
  { name: 'Frozen Pie', category: CATEGORIES.FROZEN, commonUnits: ['pc', 'oz'] },
  { name: 'Frozen Cake', category: CATEGORIES.FROZEN, commonUnits: ['pc', 'oz'] },
  { name: 'Frozen Cookie Dough', category: CATEGORIES.FROZEN, commonUnits: ['pkg', 'oz', 'pc'] },
  { name: 'Frozen Biscuits', category: CATEGORIES.FROZEN, commonUnits: ['can', 'pc', 'oz'] },
  { name: 'Frozen Dinner Rolls', category: CATEGORIES.FROZEN, commonUnits: ['pc', 'oz'] },
  { name: 'Frozen Bread Dough', category: CATEGORIES.FROZEN, commonUnits: ['loaf', 'oz'] },

  // SPICES (80+ items)
  { name: 'Salt', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'cup', 'g', 'pinch'] },
  { name: 'Black Pepper', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g', 'pinch'] },
  { name: 'White Pepper', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Red Pepper Flakes', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g', 'pinch'] },
  { name: 'Cayenne Pepper', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g', 'pinch'] },
  { name: 'Paprika', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Smoked Paprika', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Cumin', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Coriander', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Turmeric', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Cinnamon', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g', 'stick'] },
  { name: 'Nutmeg', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g', 'whole'] },
  { name: 'Cloves', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g', 'whole'] },
  { name: 'Allspice', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Cardamom', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g', 'pod'] },
  { name: 'Ginger Powder', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Garlic Powder', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Onion Powder', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Chili Powder', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Curry Powder', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Garam Masala', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Italian Seasoning', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Herbs de Provence', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Old Bay Seasoning', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Cajun Seasoning', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Taco Seasoning', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g', 'pkg'] },
  { name: 'Ranch Seasoning', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g', 'pkg'] },
  { name: 'Oregano', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Basil', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Thyme', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Rosemary', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Sage', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Marjoram', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Tarragon', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Bay Leaves', category: CATEGORIES.SPICES, commonUnits: ['pc', 'g'] },
  { name: 'Dill Weed', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Parsley Flakes', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Celery Seed', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Mustard Seed', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Fennel Seed', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Caraway Seed', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Poppy Seed', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Sesame Seeds', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'cup', 'g'] },
  { name: 'Vanilla Extract', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'oz', 'ml'] },
  { name: 'Almond Extract', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'oz'] },
  { name: 'Peppermint Extract', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'oz'] },
  { name: 'Lemon Extract', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'oz'] },
  { name: 'Cocoa Powder', category: CATEGORIES.SPICES, commonUnits: ['cup', 'tbsp', 'g', 'oz'] },
  { name: 'Baking Powder', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'cup', 'g'] },
  { name: 'Baking Soda', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'cup', 'g'] },
  { name: 'Cream of Tartar', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Yeast', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'pkg', 'g'] },
  { name: 'Saffron', category: CATEGORIES.SPICES, commonUnits: ['pinch', 'thread', 'g'] },
  { name: 'Star Anise', category: CATEGORIES.SPICES, commonUnits: ['pc', 'g'] },
  { name: 'Five Spice Powder', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Wasabi Powder', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Sumac', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Za\'atar', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Smoked Salt', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Garlic Salt', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Onion Salt', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Celery Salt', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Seasoned Salt', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Lemon Pepper', category: CATEGORIES.SPICES, commonUnits: ['tsp', 'tbsp', 'g'] },

  // PANTRY (100+ items)
  { name: 'All-Purpose Flour', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz', 'lbs'] },
  { name: 'Bread Flour', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz', 'lbs'] },
  { name: 'Whole Wheat Flour', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz', 'lbs'] },
  { name: 'Cake Flour', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Self-Rising Flour', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Almond Flour', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Coconut Flour', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Cornmeal', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Cornstarch', category: CATEGORIES.PANTRY, commonUnits: ['tbsp', 'cup', 'g', 'oz'] },
  { name: 'Sugar', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'tsp', 'g', 'lbs'] },
  { name: 'Brown Sugar', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'g', 'lbs'] },
  { name: 'Powdered Sugar', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'g', 'oz'] },
  { name: 'Honey', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'tsp', 'oz'] },
  { name: 'Maple Syrup', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'tsp', 'oz'] },
  { name: 'Agave Nectar', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'tsp', 'oz'] },
  { name: 'Molasses', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'tsp', 'oz'] },
  { name: 'Corn Syrup', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'oz'] },
  { name: 'Rice', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz', 'lbs'] },
  { name: 'White Rice', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz', 'lbs'] },
  { name: 'Brown Rice', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz', 'lbs'] },
  { name: 'Basmati Rice', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz', 'lbs'] },
  { name: 'Jasmine Rice', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz', 'lbs'] },
  { name: 'Arborio Rice', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Wild Rice', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Pasta', category: CATEGORIES.PANTRY, commonUnits: ['oz', 'g', 'lbs', 'pkg'] },
  { name: 'Spaghetti', category: CATEGORIES.PANTRY, commonUnits: ['oz', 'g', 'lbs'] },
  { name: 'Penne', category: CATEGORIES.PANTRY, commonUnits: ['oz', 'g', 'cup'] },
  { name: 'Fettuccine', category: CATEGORIES.PANTRY, commonUnits: ['oz', 'g', 'lbs'] },
  { name: 'Linguine', category: CATEGORIES.PANTRY, commonUnits: ['oz', 'g', 'lbs'] },
  { name: 'Rigatoni', category: CATEGORIES.PANTRY, commonUnits: ['oz', 'g', 'cup'] },
  { name: 'Macaroni', category: CATEGORIES.PANTRY, commonUnits: ['oz', 'g', 'cup'] },
  { name: 'Lasagna Noodles', category: CATEGORIES.PANTRY, commonUnits: ['oz', 'g', 'sheet'] },
  { name: 'Angel Hair', category: CATEGORIES.PANTRY, commonUnits: ['oz', 'g', 'lbs'] },
  { name: 'Orzo', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'oz', 'g'] },
  { name: 'Egg Noodles', category: CATEGORIES.PANTRY, commonUnits: ['oz', 'g', 'cup'] },
  { name: 'Ramen Noodles', category: CATEGORIES.PANTRY, commonUnits: ['pkg', 'oz'] },
  { name: 'Quinoa', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Couscous', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Bulgur', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Farro', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Barley', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Oats', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Rolled Oats', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Steel Cut Oats', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Instant Oats', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz', 'pkg'] },
  { name: 'Polenta', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Grits', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Lentils', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz', 'lbs'] },
  { name: 'Red Lentils', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Green Lentils', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Split Peas', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz'] },
  { name: 'Dried Beans', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'g', 'oz', 'lbs'] },
  { name: 'Olive Oil', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'tsp', 'ml', 'oz'] },
  { name: 'Vegetable Oil', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'ml', 'oz'] },
  { name: 'Canola Oil', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'ml', 'oz'] },
  { name: 'Coconut Oil', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'tsp', 'g', 'oz'] },
  { name: 'Avocado Oil', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'ml', 'oz'] },
  { name: 'Sesame Oil', category: CATEGORIES.PANTRY, commonUnits: ['tbsp', 'tsp', 'ml', 'oz'] },
  { name: 'Peanut Oil', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'ml', 'oz'] },
  { name: 'Sunflower Oil', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'ml', 'oz'] },
  { name: 'Grapeseed Oil', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'ml', 'oz'] },
  { name: 'Vinegar', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'tsp', 'ml', 'oz'] },
  { name: 'White Vinegar', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'ml', 'oz'] },
  { name: 'Apple Cider Vinegar', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'tsp', 'ml', 'oz'] },
  { name: 'Balsamic Vinegar', category: CATEGORIES.PANTRY, commonUnits: ['tbsp', 'tsp', 'ml', 'oz'] },
  { name: 'Red Wine Vinegar', category: CATEGORIES.PANTRY, commonUnits: ['tbsp', 'tsp', 'ml', 'oz'] },
  { name: 'White Wine Vinegar', category: CATEGORIES.PANTRY, commonUnits: ['tbsp', 'tsp', 'ml', 'oz'] },
  { name: 'Rice Vinegar', category: CATEGORIES.PANTRY, commonUnits: ['tbsp', 'tsp', 'ml', 'oz'] },
  { name: 'Soy Sauce', category: CATEGORIES.PANTRY, commonUnits: ['tbsp', 'tsp', 'cup', 'ml', 'oz'] },
  { name: 'Worcestershire Sauce', category: CATEGORIES.PANTRY, commonUnits: ['tbsp', 'tsp', 'oz'] },
  { name: 'Fish Sauce', category: CATEGORIES.PANTRY, commonUnits: ['tbsp', 'tsp', 'ml', 'oz'] },
  { name: 'Hot Sauce', category: CATEGORIES.PANTRY, commonUnits: ['tsp', 'tbsp', 'oz', 'dash'] },
  { name: 'Sriracha', category: CATEGORIES.PANTRY, commonUnits: ['tsp', 'tbsp', 'oz'] },
  { name: 'Ketchup', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'tsp', 'oz'] },
  { name: 'Mustard', category: CATEGORIES.PANTRY, commonUnits: ['tbsp', 'tsp', 'oz'] },
  { name: 'Dijon Mustard', category: CATEGORIES.PANTRY, commonUnits: ['tbsp', 'tsp', 'oz'] },
  { name: 'Yellow Mustard', category: CATEGORIES.PANTRY, commonUnits: ['tbsp', 'tsp', 'oz'] },
  { name: 'Whole Grain Mustard', category: CATEGORIES.PANTRY, commonUnits: ['tbsp', 'tsp', 'oz'] },
  { name: 'Mayonnaise', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'tsp', 'oz'] },
  { name: 'Peanut Butter', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'tsp', 'oz'] },
  { name: 'Almond Butter', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'tbsp', 'tsp', 'oz'] },
  { name: 'Nutella', category: CATEGORIES.PANTRY, commonUnits: ['tbsp', 'tsp', 'oz'] },
  { name: 'Jam', category: CATEGORIES.PANTRY, commonUnits: ['tbsp', 'tsp', 'cup', 'oz'] },
  { name: 'Jelly', category: CATEGORIES.PANTRY, commonUnits: ['tbsp', 'tsp', 'cup', 'oz'] },
  { name: 'Chocolate Chips', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'oz', 'g'] },
  { name: 'Nuts', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'oz', 'g'] },
  { name: 'Almonds', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'oz', 'g'] },
  { name: 'Walnuts', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'oz', 'g'] },
  { name: 'Pecans', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'oz', 'g'] },
  { name: 'Cashews', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'oz', 'g'] },
  { name: 'Peanuts', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'oz', 'g'] },
  { name: 'Pistachios', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'oz', 'g'] },
  { name: 'Pine Nuts', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'oz', 'g', 'tbsp'] },
  { name: 'Hazelnuts', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'oz', 'g'] },
  { name: 'Macadamia Nuts', category: CATEGORIES.PANTRY, commonUnits: ['cup', 'oz', 'g'] },

  // OTHER (40+ items)
  { name: 'Coffee', category: CATEGORIES.OTHER, commonUnits: ['cup', 'g', 'oz', 'tbsp'] },
  { name: 'Tea', category: CATEGORIES.OTHER, commonUnits: ['bag', 'tsp', 'cup'] },
  { name: 'Green Tea', category: CATEGORIES.OTHER, commonUnits: ['bag', 'tsp', 'cup'] },
  { name: 'Black Tea', category: CATEGORIES.OTHER, commonUnits: ['bag', 'tsp', 'cup'] },
  { name: 'Herbal Tea', category: CATEGORIES.OTHER, commonUnits: ['bag', 'tsp', 'cup'] },
  { name: 'Water', category: CATEGORIES.OTHER, commonUnits: ['cup', 'ml', 'liter', 'oz', 'gal'] },
  { name: 'Sparkling Water', category: CATEGORIES.OTHER, commonUnits: ['cup', 'ml', 'oz', 'can'] },
  { name: 'Juice', category: CATEGORIES.OTHER, commonUnits: ['cup', 'ml', 'oz', 'liter'] },
  { name: 'Orange Juice', category: CATEGORIES.OTHER, commonUnits: ['cup', 'ml', 'oz'] },
  { name: 'Apple Juice', category: CATEGORIES.OTHER, commonUnits: ['cup', 'ml', 'oz'] },
  { name: 'Cranberry Juice', category: CATEGORIES.OTHER, commonUnits: ['cup', 'ml', 'oz'] },
  { name: 'Grape Juice', category: CATEGORIES.OTHER, commonUnits: ['cup', 'ml', 'oz'] },
  { name: 'Lemonade', category: CATEGORIES.OTHER, commonUnits: ['cup', 'ml', 'oz'] },
  { name: 'Soda', category: CATEGORIES.OTHER, commonUnits: ['can', 'bottle', 'cup', 'ml', 'oz'] },
  { name: 'Wine', category: CATEGORIES.OTHER, commonUnits: ['cup', 'ml', 'oz', 'bottle'] },
  { name: 'Red Wine', category: CATEGORIES.OTHER, commonUnits: ['cup', 'ml', 'oz', 'bottle'] },
  { name: 'White Wine', category: CATEGORIES.OTHER, commonUnits: ['cup', 'ml', 'oz', 'bottle'] },
  { name: 'Beer', category: CATEGORIES.OTHER, commonUnits: ['can', 'bottle', 'cup', 'ml', 'oz'] },
  { name: 'Sake', category: CATEGORIES.OTHER, commonUnits: ['cup', 'ml', 'oz'] },
  { name: 'Rum', category: CATEGORIES.OTHER, commonUnits: ['oz', 'ml', 'shot'] },
  { name: 'Vodka', category: CATEGORIES.OTHER, commonUnits: ['oz', 'ml', 'shot'] },
  { name: 'Whiskey', category: CATEGORIES.OTHER, commonUnits: ['oz', 'ml', 'shot'] },
  { name: 'Brandy', category: CATEGORIES.OTHER, commonUnits: ['oz', 'ml', 'shot'] },
  { name: 'Tequila', category: CATEGORIES.OTHER, commonUnits: ['oz', 'ml', 'shot'] },
  { name: 'Gin', category: CATEGORIES.OTHER, commonUnits: ['oz', 'ml', 'shot'] },
  { name: 'Tofu', category: CATEGORIES.OTHER, commonUnits: ['block', 'oz', 'g', 'cup'] },
  { name: 'Tempeh', category: CATEGORIES.OTHER, commonUnits: ['oz', 'g', 'cup'] },
  { name: 'Seitan', category: CATEGORIES.OTHER, commonUnits: ['oz', 'g', 'cup'] },
  { name: 'Nutritional Yeast', category: CATEGORIES.OTHER, commonUnits: ['tbsp', 'cup', 'g'] },
  { name: 'Miso Paste', category: CATEGORIES.OTHER, commonUnits: ['tbsp', 'tsp', 'g', 'oz'] },
  { name: 'Tahini', category: CATEGORIES.OTHER, commonUnits: ['tbsp', 'cup', 'g', 'oz'] },
  { name: 'Hummus', category: CATEGORIES.OTHER, commonUnits: ['tbsp', 'cup', 'oz'] },
  { name: 'Protein Powder', category: CATEGORIES.OTHER, commonUnits: ['scoop', 'tbsp', 'g'] },
  { name: 'Gelatin', category: CATEGORIES.OTHER, commonUnits: ['packet', 'tbsp', 'g'] },
  { name: 'Agar Agar', category: CATEGORIES.OTHER, commonUnits: ['tsp', 'tbsp', 'g'] },
  { name: 'Xanthan Gum', category: CATEGORIES.OTHER, commonUnits: ['tsp', 'g'] },
  { name: 'Arrowroot Powder', category: CATEGORIES.OTHER, commonUnits: ['tbsp', 'cup', 'g'] },
  { name: 'Tapioca Starch', category: CATEGORIES.OTHER, commonUnits: ['tbsp', 'cup', 'g'] },
  { name: 'Potato Starch', category: CATEGORIES.OTHER, commonUnits: ['tbsp', 'cup', 'g'] },
  { name: 'Vital Wheat Gluten', category: CATEGORIES.OTHER, commonUnits: ['cup', 'tbsp', 'g'] },
];

// Tag Categories
const tagCategories = [
  { name: 'Time/Effort', slug: 'time-effort', sortOrder: 1 },
  { name: 'Diet/Health', slug: 'diet-health', sortOrder: 2 },
  { name: 'Dish Type', slug: 'dish-type', sortOrder: 3 },
  { name: 'Occasion', slug: 'occasion', sortOrder: 4 },
  { name: 'World Cuisine', slug: 'world-cuisine', sortOrder: 5 },
  { name: 'Budget', slug: 'budget', sortOrder: 6 },
];

async function seedTagCategories() {
  console.log('🏷️  Seeding tag categories...');

  const result = await prisma.tagCategory.createMany({
    data: tagCategories,
    skipDuplicates: true,
  });

  console.log(`✅ Seeded ${result.count} tag categories`);
  return await prisma.tagCategory.findMany();
}

async function seedSystemTags(categories: any[]) {
  console.log('🏷️  Seeding system tags...');

  const categoryMap = categories.reduce((acc, cat) => {
    acc[cat.slug] = cat.id;
    return acc;
  }, {} as Record<string, string>);

  const systemTags = [
    // Time/Effort (15 tags)
    { categoryId: categoryMap['time-effort'], name: 'Quick (<15 min)', slug: 'quick', isSystem: true, userId: null },
    { categoryId: categoryMap['time-effort'], name: 'Medium (15-45 min)', slug: 'medium', isSystem: true, userId: null },
    { categoryId: categoryMap['time-effort'], name: 'Long (>45 min)', slug: 'long', isSystem: true, userId: null },
    { categoryId: categoryMap['time-effort'], name: 'Easy', slug: 'easy', isSystem: true, userId: null },
    { categoryId: categoryMap['time-effort'], name: 'Moderate', slug: 'moderate', isSystem: true, userId: null },
    { categoryId: categoryMap['time-effort'], name: 'Advanced', slug: 'advanced', isSystem: true, userId: null },
    { categoryId: categoryMap['time-effort'], name: 'One-Pot', slug: 'one-pot', isSystem: true, userId: null },
    { categoryId: categoryMap['time-effort'], name: 'No-Cook', slug: 'no-cook', isSystem: true, userId: null },
    { categoryId: categoryMap['time-effort'], name: 'Make-Ahead', slug: 'make-ahead', isSystem: true, userId: null },
    { categoryId: categoryMap['time-effort'], name: 'Batch Cooking', slug: 'batch-cooking', isSystem: true, userId: null },
    { categoryId: categoryMap['time-effort'], name: 'Slow Cooker', slug: 'slow-cooker', isSystem: true, userId: null },
    { categoryId: categoryMap['time-effort'], name: 'Instant Pot', slug: 'instant-pot', isSystem: true, userId: null },
    { categoryId: categoryMap['time-effort'], name: 'Air Fryer', slug: 'air-fryer', isSystem: true, userId: null },
    { categoryId: categoryMap['time-effort'], name: '5 Ingredients', slug: '5-ingredients', isSystem: true, userId: null },
    { categoryId: categoryMap['time-effort'], name: '30 Minutes or Less', slug: '30-min-or-less', isSystem: true, userId: null },

    // Diet/Health (20 tags)
    { categoryId: categoryMap['diet-health'], name: 'Vegetarian', slug: 'vegetarian', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Vegan', slug: 'vegan', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Pescatarian', slug: 'pescatarian', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Gluten-Free', slug: 'gluten-free', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Dairy-Free', slug: 'dairy-free', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Nut-Free', slug: 'nut-free', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Egg-Free', slug: 'egg-free', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Low-Carb', slug: 'low-carb', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Keto', slug: 'keto', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Paleo', slug: 'paleo', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Whole30', slug: 'whole30', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Halal', slug: 'halal', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Kosher', slug: 'kosher', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'High-Protein', slug: 'high-protein', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Low-Calorie', slug: 'low-calorie', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Heart-Healthy', slug: 'heart-healthy', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Sugar-Free', slug: 'sugar-free', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Low-Sodium', slug: 'low-sodium', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Anti-Inflammatory', slug: 'anti-inflammatory', isSystem: true, userId: null },
    { categoryId: categoryMap['diet-health'], name: 'Raw Food', slug: 'raw-food', isSystem: true, userId: null },

    // Dish Type (25 tags)
    { categoryId: categoryMap['dish-type'], name: 'Breakfast', slug: 'breakfast', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Brunch', slug: 'brunch', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Lunch', slug: 'lunch', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Dinner', slug: 'dinner', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Snack', slug: 'snack', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Appetizer', slug: 'appetizer', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Main Course', slug: 'main-course', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Side Dish', slug: 'side-dish', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Dessert', slug: 'dessert', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Soup', slug: 'soup', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Salad', slug: 'salad', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Sandwich', slug: 'sandwich', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Pasta', slug: 'pasta', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Pizza', slug: 'pizza', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Burger', slug: 'burger', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Taco/Burrito', slug: 'taco-burrito', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Stir-Fry', slug: 'stir-fry', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Curry', slug: 'curry', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Stew', slug: 'stew', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Casserole', slug: 'casserole', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Baked Goods', slug: 'baked-goods', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Beverage', slug: 'beverage', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Cocktail', slug: 'cocktail', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Smoothie', slug: 'smoothie', isSystem: true, userId: null },
    { categoryId: categoryMap['dish-type'], name: 'Sauce/Condiment', slug: 'sauce-condiment', isSystem: true, userId: null },

    // Occasion (15 tags)
    { categoryId: categoryMap['occasion'], name: 'Weeknight', slug: 'weeknight', isSystem: true, userId: null },
    { categoryId: categoryMap['occasion'], name: 'Weekend', slug: 'weekend', isSystem: true, userId: null },
    { categoryId: categoryMap['occasion'], name: 'Quick Meal', slug: 'quick-meal', isSystem: true, userId: null },
    { categoryId: categoryMap['occasion'], name: 'Party', slug: 'party', isSystem: true, userId: null },
    { categoryId: categoryMap['occasion'], name: 'Holiday', slug: 'holiday', isSystem: true, userId: null },
    { categoryId: categoryMap['occasion'], name: 'Birthday', slug: 'birthday', isSystem: true, userId: null },
    { categoryId: categoryMap['occasion'], name: 'BBQ', slug: 'bbq', isSystem: true, userId: null },
    { categoryId: categoryMap['occasion'], name: 'Picnic', slug: 'picnic', isSystem: true, userId: null },
    { categoryId: categoryMap['occasion'], name: 'Potluck', slug: 'potluck', isSystem: true, userId: null },
    { categoryId: categoryMap['occasion'], name: 'Meal Prep', slug: 'meal-prep', isSystem: true, userId: null },
    { categoryId: categoryMap['occasion'], name: 'Freezer-Friendly', slug: 'freezer-friendly', isSystem: true, userId: null },
    { categoryId: categoryMap['occasion'], name: 'Leftovers', slug: 'leftovers', isSystem: true, userId: null },
    { categoryId: categoryMap['occasion'], name: 'Date Night', slug: 'date-night', isSystem: true, userId: null },
    { categoryId: categoryMap['occasion'], name: 'Kids-Friendly', slug: 'kids-friendly', isSystem: true, userId: null },
    { categoryId: categoryMap['occasion'], name: 'Family Dinner', slug: 'family-dinner', isSystem: true, userId: null },

    // World Cuisine (30 tags)
    { categoryId: categoryMap['world-cuisine'], name: 'Italian', slug: 'italian', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'French', slug: 'french', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Spanish', slug: 'spanish', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Greek', slug: 'greek', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Mediterranean', slug: 'mediterranean', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Mexican', slug: 'mexican', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Latin American', slug: 'latin-american', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Caribbean', slug: 'caribbean', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Chinese', slug: 'chinese', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Japanese', slug: 'japanese', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Korean', slug: 'korean', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Thai', slug: 'thai', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Vietnamese', slug: 'vietnamese', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Indian', slug: 'indian', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Middle Eastern', slug: 'middle-eastern', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Moroccan', slug: 'moroccan', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Ethiopian', slug: 'ethiopian', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'American', slug: 'american', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Southern', slug: 'southern', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Tex-Mex', slug: 'tex-mex', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'German', slug: 'german', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'British', slug: 'british', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Irish', slug: 'irish', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Polish', slug: 'polish', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Russian', slug: 'russian', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Turkish', slug: 'turkish', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Brazilian', slug: 'brazilian', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Peruvian', slug: 'peruvian', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Filipino', slug: 'filipino', isSystem: true, userId: null },
    { categoryId: categoryMap['world-cuisine'], name: 'Fusion', slug: 'fusion', isSystem: true, userId: null },

    // Budget (6 tags)
    { categoryId: categoryMap['budget'], name: 'Budget-Friendly', slug: 'budget-friendly', isSystem: true, userId: null },
    { categoryId: categoryMap['budget'], name: 'Moderate', slug: 'moderate-budget', isSystem: true, userId: null },
    { categoryId: categoryMap['budget'], name: 'Premium', slug: 'premium', isSystem: true, userId: null },
    { categoryId: categoryMap['budget'], name: 'Pantry Staples', slug: 'pantry-staples', isSystem: true, userId: null },
    { categoryId: categoryMap['budget'], name: 'Seasonal', slug: 'seasonal', isSystem: true, userId: null },
    { categoryId: categoryMap['budget'], name: 'Luxury Ingredients', slug: 'luxury-ingredients', isSystem: true, userId: null },
  ];

  const result = await prisma.tag.createMany({
    data: systemTags,
    skipDuplicates: true,
  });

  console.log(`✅ Seeded ${result.count} system tags (Total: ${systemTags.length} tags)`);
  return systemTags.length;
}

async function main() {
  console.log('🌱 Starting database seed...');

  try {
    // Seed ingredients
    console.log('\n📦 Seeding ingredients...');
    const ingredientResult = await prisma.ingredient.createMany({
      data: ingredients,
      skipDuplicates: true,
    });
    console.log(`✅ Successfully seeded ${ingredientResult.count} ingredients!`);

    // Verify ingredient category distribution
    const categoryCounts = await prisma.ingredient.groupBy({
      by: ['category'],
      _count: true,
    });

    console.log('\n📊 Ingredient distribution by category:');
    categoryCounts.forEach(({ category, _count }) => {
      console.log(`  - ${category}: ${_count} ingredients`);
    });

    const totalIngredients = await prisma.ingredient.count();
    console.log(`\n📈 Total ingredients in database: ${totalIngredients}`);

    // Seed tag categories
    console.log('\n');
    const categories = await seedTagCategories();

    // Seed system tags
    await seedSystemTags(categories);

    // Verify tag data
    const tagCount = await prisma.tag.count({ where: { isSystem: true } });
    const categoryCount = await prisma.tagCategory.count();

    console.log(`\n📊 Tag system summary:`);
    console.log(`  - Tag categories: ${categoryCount}`);
    console.log(`  - System tags: ${tagCount}`);

  } catch (error) {
    console.error('❌ Error seeding database:', error);
    throw error;
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
    console.log('\n✨ Seed completed successfully!');
  })
  .catch(async (error) => {
    console.error('\n💥 Seed failed:', error);
    await prisma.$disconnect();
    process.exit(1);
  });
